Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.hostname = "automl-master"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "automl-master"
    vb.gui = false
  end

  config.vm.synced_folder "./experiments", "/home/vagrant/experiments",
    create: true, owner: "vagrant", group: "vagrant"

  config.vm.synced_folder "./mlflow_artifacts", "/home/vagrant/mlflow/artifacts",
    create: true, owner: "vagrant", group: "vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    systemctl enable docker
    systemctl start docker
    usermod -aG docker vagrant
    apt-get install -y python3-pip python3-venv
    pip3 install mlflow scikit-learn pandas numpy xgboost lightgbm
  SHELL
end
